# Custom aliases

alias rst="source ~/.zshrc; clear"
alias zc="vim ~/.zshrc"
alias zt="vim ~/.oh-my-zsh/custom/themes/vg_custom.zsh-theme"
alias zf="vim ~/.oh-my-zsh/custom/func.zsh"
alias za="vim ~/.oh-my-zsh/custom/aliases.zsh"

alias gd="git diff"
alias gs="git status"
alias gb="git branch"
alias gbd="git branch -d"
alias gbdd="git branch -D"
alias gco="git checkout"
alias gm="git checkout master"
alias gbn="git checkout -b"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gca="git commit -a"
alias gcm="git commit -m"
alias gcam="git commit -am"
alias gcma="git commit -am"
alias gp="git push"
alias gpu="git push -u"
alias gpl="git pull"
alias gss="git stash save"
alias gsl="git stash list"
alias gsa="git stash apply"
alias gsp="git stash pop"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glp="gl -p"

alias ns="npm start"
alias nsd="npm start dev"
alias ni="npm install"
alias nr="npm run"
alias nd="npm run dropdb dev"
alias nu="npm i -g npm"

alias pinit="pod init"
alias pi="pod install"
alias pu="pod update"
alias po="pod outdated"
alias pd="pod deintegrate"
alias pe="pod env"
alias ps="pod search"
alias pl="pod list"

